#!/usr/bin/env ruby

require 'rubygems' if RUBY_VERSION < '1.9.0'
require 'optparse'

options = {}

optparse = OptionParser.new do |opts|
  opts.on('-h', '--help', 'Display this screen') do
    puts opts
    exit
  end

  opts.on('-c', '--client NAME', 'Client NAME') do |client|
    options[:client] = client
  end
end

optparse.parse!

unless options[:client]
  puts "You must supply a client name"
  exit
end

time = (0..30).to_a.sample

case (0..2).to_a.sample
when 0
  sleep(time)
  puts "Everything is just peachy :D (sleep: #{time}) (client: #{options[:client]})"
  exit
when 1
  sleep(time)
  puts "Something may be wrong :/ (sleep: #{time}) (client: #{options[:client]})"
  exit 1
when 2
  sleep(time)
  puts "GET TO DA CHOPPA! 0_0 (sleep: #{time}) (client: #{options[:client]})"
  exit 2
end
